DROP TABLE IF EXISTS breaks;
DROP TABLE IF EXISTS attendance;

DROP FUNCTION IF EXISTS update_updated_at_column;
DROP TRIGGER IF EXISTS UPDATE_ATTENDANCE_MODTIME ON attendance;
DROP TRIGGER IF EXISTS UPDATE_BREAKS_MODTIME ON breaks;